config/routes.rb
ConcertTracker::Application.routes.draw do

  root 'concerts#index'
  resources :concerts do
    resources :bands
  end
  

end

app/models/band.rb
class Band < ActiveRecord::Base
  validates :name, presence: true

  belongs_to :concert
end

app/models/concert.rb
class Concert < ActiveRecord::Base
  validates :venue, :location, :date, presence: true

  has_many :bands, dependent: :destroy

  def self.attended
    where("date <= ?", Time.now).order("date desc")
  end

  def num_of_bands
    bands.size
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/bands_controller.rb
class BandsController < ApplicationController
  before_action :set_concert
  
  def index
    @bands = @concert.bands
  end

  def new
    @band = @concert.bands.new
  end

  def create
    @band = @concert.bands.new(band_attributes)
    if @band.save
      redirect_to concert_bands_path(@concert), notice: "Band has successfully been added!"
    else
      render :new
    end
  end

private

  def set_concert
    @concert = Concert.find(params[:concert_id])
  end

  def band_attributes
    params.require(:band).permit(:name)
  end

end

app/controllers/concerts_controller.rb
class ConcertsController < ApplicationController
  def index
    @concerts = Concert.attended
  end

  def show
    @concert = Concert.find(params[:id])
  end

  def edit
    @concert = Concert.find(params[:id])
  end

  def update
    @concert = Concert.find(params[:id])
    if @concert.update(concert_params)
      redirect_to @concert, notice: "Concert successfully updated!"
    else
      render :edit
    end
  end

  def new
    @concert = Concert.new
  end

  def create
    @concert = Concert.new(concert_params)
    if @concert.save
      redirect_to @concert, notice: "Concert successfully created!"
    else
      render :new
    end
  end

  def destroy
    @concert = Concert.find(params[:id])
    @concert.destroy
    redirect_to concerts_url, alert: "Concert successfully deleted!"
  end

private

  def concert_params
    params.require(:concert).permit(:venue, :location, :date)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bands_helper.rb
module BandsHelper
end

app/helpers/concerts_helper.rb
module ConcertsHelper
end

app/views/bands/index.html.erb
<h1>Bands on <%= link_to @concert.date, @concert %></h1>

<% @bands.each do |band| %>
  <p><%= band.name %></p>
<% end %>

app/views/bands/new.html.erb
<h1>Add Band for <%= link_to @concert.date, @concert %></h1>

<%= form_for([@concert, @band]) do |f| %>
  <%= render "shared/errors", object: @band %>
  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name, autofocus: true %>
  </p>
  <p>
    <%= f.submit "Add Band" %> |
    <%= link_to "Cancel", concert_path(@concert) %>
  </p>
<% end %>

app/views/concerts/_form.html.erb
<%= form_for(@concert) do |f| %>
  <%= render "shared/errors", object: @concert %>
  <p>
    <%= f.label :venue %><br />
    <%= f.text_field :venue, autofocus: true %>
  </p>
  <p>
    <%= f.label :location %><br />
    <%= f.text_field :location %>
  </p>
  <p>
    <%= f.label :date %><br />
    <%= f.date_field :date %>
  </p>
  <p>
    <%= f.submit %> |
    <%= link_to "Cancel", concerts_path %>
  </p>
<% end %>

app/views/concerts/edit.html.erb
<h1>Editing Concert: <%= @concert.date %></h1>

<%= render "form" %>

app/views/concerts/index.html.erb
<h1><%= pluralize(@concerts.size, "Concert") %></h1>

<ul>
  <% @concerts.each do |concert| %>
    <p><%= link_to concert.date, concert %> - <%= pluralize(concert.num_of_bands, "band") %></p>
    <p><%= concert.venue %> | <%= concert.location %></p>    
  <% end %>
</ul>

app/views/concerts/new.html.erb
<h1>Create Concert</h1>

<%= render "form" %>

app/views/concerts/show.html.erb
<h1><%= @concert.date %></h1>

<p><%= @concert.venue %> | <%= @concert.location %></p>

<p><%= link_to pluralize(@concert.bands.size, "Band"), concert_bands_path(@concert) %></p>

<% @concert.bands.each do |band| %>
  <p>- <%= band.name %></p>
<% end %>

<p><%= link_to "Add Band", new_concert_band_path(@concert) %></p>

<%= link_to "Edit", edit_concert_path(@concert) %> |
<%= link_to "Delete", concert_path(@concert), method: :delete, data: { confirm: 'Are you sure?' } %>

app/views/layouts/_flashes.html.erb
<% flash.each do |key, value| %>
  <%= content_tag(:p, value, class: "alert alert-#{key}") %>
<% end %>

app/views/layouts/_footer.html.erb
<footer id="page-footer">
  <p>
    Copyright &copy; 2014
    <%= link_to 'Wheatbox Studios', 'http://wheatboxstudios.com' %>
  </p>
</footer>

app/views/layouts/_header.html.erb
<header id="page-header">
  <h1>Concert Tracker</h1>
</header>

app/views/layouts/_sidebar.html.erb
<aside id="sidebar">
  <nav>
    <ul>
      <li>
        <%= link_to "All Concerts", concerts_path %>
      </li>
      <li>
        <%= link_to "Add New Concert", new_concert_path %>
      </li>
    </ul>
  </nav>
</aside>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ConcertTracker</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <%= render "layouts/header" %>
    <%= render "layouts/flashes" %>
    <%= render "layouts/sidebar" %>
    <%= yield %>
    <%= render "layouts/footer" %>
  </div>
</body>
</html>

app/views/shared/_errors.html.erb
<% if object.errors.any? %>
<section id="errors">
  <header>
    <h2>
      Oops! The <%= object.class.name.humanize.downcase %> could not be saved. 
    </h2>
    <h3>
      Please correct the following <%= pluralize(object.errors.count, "error") %>:
    </h3>
  </header>
  <ul>
    <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
</section>
<% end %>